version: '3.8'

services:
  backend:
    image: eclipse-temurin:21-jdk
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      - PORT=8080
      - CORS_ALLOWED_ORIGINS=http://localhost:8065,http://frontend:3000
    command: >
      bash -c "chmod +x ./mvnw &&
               ./mvnw spring-boot:run"
    networks:
      - app-network

  frontend:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./client:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8065/api
    command: >
      sh -c "apk add --no-cache yarn &&
             yarn install &&
             yarn dev"
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "8065:8065"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  app-network:
    driver: bridge