spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:myapp}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: ${PORT:8080}
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: ${JWT_SECRET:c8d15ec8b80f46f2952c3f3b6d0794342459b6742df52173753011d861d4f17a}
  expiration: ${JWT_EXPIRATION:86400000}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:8065,http://localhost:3000}

logging:
  level:
    root: INFO
    io.bootify.my_app: DEBUG
    io.bootify.my_app.config: DEBUG
    org.springframework.web: DEBUG
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    org.springframework.web.servlet: DEBUG
    org.hibernate: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

debug: true
